name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Build and package (Linux)
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        sudo apt-get install libgles2-mesa-dev libx11-dev
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -Dramses-logic_PACKAGE_TYPE=DEB
        cmake --build . --target package --config $BUILD_TYPE
      if: ${{ matrix.os == 'ubuntu-18.04' }}

    - name: Build and package (Windows)
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -Dramses-logic_PACKAGE_TYPE=ZIP \
            -DCMAKE_CONFIGURATION_TYPES=Release
        cmake --build . --target package --config $BUILD_TYPE
      if: ${{ matrix.os == 'windows-latest' }}

    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{runner.workspace}}/build/RamsesLogic-*.deb
          ${{runner.workspace}}/build/RamsesLogic-*.zip
